= Changelog
All notable changes to this project will be documented in this file since 
July 11 of 2019 (2019-07-11).

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog],
and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].

== [Unreleased]

== [0.2.0] - 2019-07-14
=== Added
* A help section in the main app page.
** You can also access the help section with `F1`.

* New app functionalities for locking dice sets:
** Locking all of the dice
** Unlocking all of the dice
** Toggling all of the dice lock

* New keyboard shortcuts to the main app page: 
** `Ctrl + Shift + M` for adding a new die item on the currently shown die.
** `Ctrl + Shift + L` for locking all of the dice regardless of their lock status.
** `Ctrl + Shift + :` for unlocking all of the dice regardless of their lock status.
** `Ctrl + Shift + "` for toggling all of the dice locks (unlock if the die is locked, vice versa).

=== Changed
* Revise the UI (for the second time). Here's the detail of some 
of the notable UI changes:
** Change the text into icons in the buttons. It also cause the main 
UI to be shorter (which means it's also a less pain to use it in a mobile 
device).
** Also, the buttons are now into a consistent button group.
** The "Add die item" button in the die component moved inside of the die popover.
Now it feels like an proper group of actions in the popover.
** The die component also got a overhaul with the "fancy" two column into a 
simple and more comprehensive one column on bigger screens similar to the mobile 
screen format.

* The "new die" keyboard shortcut now maps to `Ctrl + Shift + N` 
(yes, that was stupid of me...)

== [0.2.0] - 2019-07-14
=== Added
* Locking function for the die in case you want to not accidentally modify the die 
(i.e. adding/removing items, editing items) or something.

* Disabling dice now prevents you from modifying anything in the die 
(it's not a bug, it's a feature, I swear...). It basically functions as a lock 
function except it doesn't count towards any of the app's operations as if it 
was deleted or never existed in the first place.

* Set a maximum length set for die name, die items, and idea set names. Here's the 
following specifications:
** For die and idea set names, *its length must be less than 64 characters*.
** For die items, *its length must be less than 32 characters*.
** There's no format for the required characters. You can put all of the exclamation marks, 
emojis, and semicolons all you want.

* 'Undo' function for previously deleted dice (you can only retrieve up to 20 recently 
deleted dice at any given time). Take note that you can only hold it in the current session. 
Changing pages or reloading will lose the deleted dice stack.

* New keyboard shortcuts to the main app page
** `Shift + N` for a new die
** `Ctrl + G` for generating an idea set
** `Ctrl + D` for clearing the generated output
** `Ctrl + S` for saving the output in the idea set database
** `Ctrl + I` for importing dice set file
** `Ctrl + E` for exporting the current dice set
** `Ctrl + Delete` for deleting the current die shown in the screen
** `Ctrl + Z` for adding back the most recent deleted die

=== Changed
* Unique ID format has been revised to base 36 to produce less data while being able 
to generate more possible combinations. It should have no effect on previously 
generated data.
** It also makes the newly generated items to have shorter names so it'll have less 
hassle of growing more room in the GUI.

* Minor refactor of components code.

* A minor revamp of the UI and improved the UX (hopefully...).
** A big detail that I want to point out here is how the remove die item button. Now 
it's constantly present with the item since it produces weird quirks 
and it just feels unnatural on the UX side.

* Use of https://tailwindcss.com[Tailwind CSS] 1.0 therefore 
https://tailwindcss.com/docs/release-notes/#tailwind-css-v1-0[big changes happened to its Tailwind config file].
** A minor site aesthetic change has also occured as a side effect of the major upgrade due to the new approach
of Tailwind CSS. Also, because of that, the UX has also improved.
